/**
 * Assistant entity types
 *
 * Assistants represent model + manually assembled context configurations.
 * They store inference parameters, tool references, and context source toggles.
 */

import * as z from 'zod'

import { UniqueModelIdSchema } from './model'

// ============================================================================
// Sub-Schemas
// ============================================================================

/** MCP server interaction mode */
export const McpModeSchema = z.enum(['disabled', 'auto', 'manual'])
export type McpMode = z.infer<typeof McpModeSchema>

/**
 * Assistant settings — inference parameters + context source toggles.
 * Stored as a single JSON column in the database.
 *
 * Default values are aligned with `DEFAULT_ASSISTANT_SETTINGS` in
 * `src/renderer/src/services/AssistantService.ts` (v1 source of truth).
 *
 * `enable*` flags control whether the corresponding parameter is sent to the model.
 * When `enable* = false`, the value is still stored but not used — the model's own
 * default takes effect. This removes the need for nullable value fields.
 */
export const AssistantSettingsSchema = z.object({
  // -- Inference parameters --
  // Defaults: AssistantService.ts L45–62, constants from config/constant.ts
  /** @default 1.0 — from DEFAULT_TEMPERATURE */
  temperature: z.number().min(0).max(2).default(1.0),
  /** @default false — disabled = use model's own default */
  enableTemperature: z.boolean().default(false),
  /** @default 1 */
  topP: z.number().min(0).max(1).default(1),
  /** @default false */
  enableTopP: z.boolean().default(false),
  // TODO: use constant instead
  /** @default 4096 — from DEFAULT_MAX_TOKENS */
  maxTokens: z.number().int().positive().default(4096),
  /** @default false — disabled = use model's own default */
  enableMaxTokens: z.boolean().default(false),
  // TODO: use constant instead
  /** @default 5 — from DEFAULT_CONTEXTCOUNT */
  contextCount: z.number().int().positive().default(5),
  /** @default true — streaming provides better UX */
  streamOutput: z.boolean().default(true),
  /** @default 'default' — let model decide.
   *  String (not enum) because providers define custom values (e.g. 'xlow', 'high-reasoning'). */
  reasoning_effort: z.string().default('default'),
  /** @default false — Qwen-specific thinking mode */
  qwenThinkMode: z.boolean().default(false),

  // -- Tool use --
  /** @default 'auto' */
  mcpMode: McpModeSchema.default('auto'),
  /** @default 'function' — gracefully falls back to prompt if not supported */
  toolUseMode: z.enum(['function', 'prompt']).default('function'),
  /** @default 20 */
  maxToolCalls: z.number().int().positive().default(20),
  /** @default true */
  enableMaxToolCalls: z.boolean().default(true),

  // -- Context sources --
  /** @default false */
  enableWebSearch: z.boolean().default(false),

  /** User-defined model parameters (e.g. {"top_k": 40, "repetition_penalty": 1.1}).
   *  Discriminated union on `type` ensures `value` is type-safe:
   *  - `string` → string value, rendered as text input
   *  - `number` → number value, rendered as number spinner
   *  - `boolean` → boolean value, rendered as toggle
   *  - `json` → arbitrary JSON value, rendered as JSON editor
   *  @default [] */
  customParameters: z
    .array(
      z.discriminatedUnion('type', [
        z.object({ name: z.string(), type: z.literal('string'), value: z.string() }),
        z.object({ name: z.string(), type: z.literal('number'), value: z.number() }),
        z.object({ name: z.string(), type: z.literal('boolean'), value: z.boolean() }),
        z.object({ name: z.string(), type: z.literal('json'), value: z.unknown() })
      ])
    )
    .default([])
})
export type AssistantSettings = z.infer<typeof AssistantSettingsSchema>

/** Pre-computed default settings object — avoids runtime parse() on every row conversion */
export const DEFAULT_ASSISTANT_SETTINGS: AssistantSettings = {
  temperature: 1.0,
  enableTemperature: false,
  topP: 1,
  enableTopP: false,
  maxTokens: 4096,
  enableMaxTokens: false,
  contextCount: 5,
  streamOutput: true,
  reasoning_effort: 'default',
  qwenThinkMode: false,
  mcpMode: 'auto',
  toolUseMode: 'function',
  maxToolCalls: 20,
  enableMaxToolCalls: true,
  enableWebSearch: false,
  customParameters: []
}

// ============================================================================
// Assistant Entity
// ============================================================================

/**
 * Complete Assistant entity as returned by the API.
 *
 * DB-nullable fields have defaults so the runtime type is always non-null.
 * `modelId` is explicitly `.nullable()` because an assistant may have no model set.
 */
export const AssistantSchema = z.object({
  /** Assistant ID (UUID v4, auto-generated by database) */
  id: z.uuidv4(),
  /** Display name */
  name: z.string().min(1),
  /** System prompt text or prompt template ID reference */
  prompt: z.string().default(''),
  /** Emoji icon for UI display */
  emoji: z.emoji().default('🌟'),
  /** Long-form description */
  description: z.string().default(''),
  /** Inference settings — model params + context toggles */
  settings: AssistantSettingsSchema,
  /** Default/primary model ID in UniqueModelId format ("providerId::modelId") */
  modelId: UniqueModelIdSchema.nullable(),
  /** Ordered MCP server IDs linked through assistant_mcp_server */
  mcpServerIds: z.array(z.string()),
  /** Ordered knowledge base IDs linked through assistant_knowledge_base */
  knowledgeBaseIds: z.array(z.string()),
  /** Creation timestamp (ISO string).
   *  DB column is nullable (SQLite integer), but rowToAssistant always provides a
   *  fallback so the API-level type is non-optional. */
  createdAt: z.iso.datetime(),
  /** Last update timestamp (ISO string). Same nullable-at-DB / non-null-at-API pattern. */
  updatedAt: z.iso.datetime()
})
export type Assistant = z.infer<typeof AssistantSchema>
