/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsWebsearchRouteImport } from './routes/settings/websearch'
import { Route as SettingsShortcutRouteImport } from './routes/settings/shortcut'
import { Route as SettingsSelectionAssistantRouteImport } from './routes/settings/selectionAssistant'
import { Route as SettingsQuickphraseRouteImport } from './routes/settings/quickphrase'
import { Route as SettingsQuickAssistantRouteImport } from './routes/settings/quickAssistant'
import { Route as SettingsProviderRouteImport } from './routes/settings/provider'
import { Route as SettingsNotesRouteImport } from './routes/settings/notes'
import { Route as SettingsModelRouteImport } from './routes/settings/model'
import { Route as SettingsMemoryRouteImport } from './routes/settings/memory'
import { Route as SettingsMcpRouteImport } from './routes/settings/mcp'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsDocprocessRouteImport } from './routes/settings/docprocess'
import { Route as SettingsDisplayRouteImport } from './routes/settings/display'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsApiServerRouteImport } from './routes/settings/api-server'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as AppTranslateRouteImport } from './routes/app/translate'
import { Route as AppNotesRouteImport } from './routes/app/notes'
import { Route as AppKnowledgeRouteImport } from './routes/app/knowledge'
import { Route as AppFilesRouteImport } from './routes/app/files'
import { Route as AppCodeRouteImport } from './routes/app/code'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppAssistantRouteImport } from './routes/app/assistant'
import { Route as SettingsWebsearchIndexRouteImport } from './routes/settings/websearch/index'
import { Route as SettingsMcpIndexRouteImport } from './routes/settings/mcp/index'
import { Route as AppPaintingsIndexRouteImport } from './routes/app/paintings/index'
import { Route as AppMinappIndexRouteImport } from './routes/app/minapp/index'
import { Route as SettingsWebsearchGeneralRouteImport } from './routes/settings/websearch/general'
import { Route as SettingsMcpServersRouteImport } from './routes/settings/mcp/servers'
import { Route as SettingsMcpNpxSearchRouteImport } from './routes/settings/mcp/npx-search'
import { Route as SettingsMcpMcpInstallRouteImport } from './routes/settings/mcp/mcp-install'
import { Route as SettingsMcpMarketplacesRouteImport } from './routes/settings/mcp/marketplaces'
import { Route as SettingsMcpBuiltinRouteImport } from './routes/settings/mcp/builtin'
import { Route as SettingsMcpSplatRouteImport } from './routes/settings/mcp/$'
import { Route as AppPaintingsSplatRouteImport } from './routes/app/paintings/$'
import { Route as AppMinappAppIdRouteImport } from './routes/app/minapp/$appId'
import { Route as SettingsWebsearchProviderProviderIdRouteImport } from './routes/settings/websearch/provider.$providerId'
import { Route as SettingsMcpSettingsServerIdRouteImport } from './routes/settings/mcp/settings.$serverId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsWebsearchRoute = SettingsWebsearchRouteImport.update({
  id: '/websearch',
  path: '/websearch',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsShortcutRoute = SettingsShortcutRouteImport.update({
  id: '/shortcut',
  path: '/shortcut',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSelectionAssistantRoute =
  SettingsSelectionAssistantRouteImport.update({
    id: '/selectionAssistant',
    path: '/selectionAssistant',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsQuickphraseRoute = SettingsQuickphraseRouteImport.update({
  id: '/quickphrase',
  path: '/quickphrase',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsQuickAssistantRoute = SettingsQuickAssistantRouteImport.update({
  id: '/quickAssistant',
  path: '/quickAssistant',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProviderRoute = SettingsProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotesRoute = SettingsNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelRoute = SettingsModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMemoryRoute = SettingsMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDocprocessRoute = SettingsDocprocessRouteImport.update({
  id: '/docprocess',
  path: '/docprocess',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDisplayRoute = SettingsDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiServerRoute = SettingsApiServerRouteImport.update({
  id: '/api-server',
  path: '/api-server',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const AppTranslateRoute = AppTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppCodeRoute = AppCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const SettingsWebsearchIndexRoute = SettingsWebsearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsWebsearchRoute,
} as any)
const SettingsMcpIndexRoute = SettingsMcpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const AppPaintingsIndexRoute = AppPaintingsIndexRouteImport.update({
  id: '/paintings/',
  path: '/paintings/',
  getParentRoute: () => AppRoute,
} as any)
const AppMinappIndexRoute = AppMinappIndexRouteImport.update({
  id: '/minapp/',
  path: '/minapp/',
  getParentRoute: () => AppRoute,
} as any)
const SettingsWebsearchGeneralRoute =
  SettingsWebsearchGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => SettingsWebsearchRoute,
  } as any)
const SettingsMcpServersRoute = SettingsMcpServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpNpxSearchRoute = SettingsMcpNpxSearchRouteImport.update({
  id: '/npx-search',
  path: '/npx-search',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpMcpInstallRoute = SettingsMcpMcpInstallRouteImport.update({
  id: '/mcp-install',
  path: '/mcp-install',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpMarketplacesRoute = SettingsMcpMarketplacesRouteImport.update({
  id: '/marketplaces',
  path: '/marketplaces',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpBuiltinRoute = SettingsMcpBuiltinRouteImport.update({
  id: '/builtin',
  path: '/builtin',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpSplatRoute = SettingsMcpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const AppPaintingsSplatRoute = AppPaintingsSplatRouteImport.update({
  id: '/paintings/$',
  path: '/paintings/$',
  getParentRoute: () => AppRoute,
} as any)
const AppMinappAppIdRoute = AppMinappAppIdRouteImport.update({
  id: '/minapp/$appId',
  path: '/minapp/$appId',
  getParentRoute: () => AppRoute,
} as any)
const SettingsWebsearchProviderProviderIdRoute =
  SettingsWebsearchProviderProviderIdRouteImport.update({
    id: '/provider/$providerId',
    path: '/provider/$providerId',
    getParentRoute: () => SettingsWebsearchRoute,
  } as any)
const SettingsMcpSettingsServerIdRoute =
  SettingsMcpSettingsServerIdRouteImport.update({
    id: '/settings/$serverId',
    path: '/settings/$serverId',
    getParentRoute: () => SettingsMcpRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/home': typeof HomeRoute
  '/settings': typeof SettingsRouteWithChildren
  '/app/assistant': typeof AppAssistantRoute
  '/app/chat': typeof AppChatRoute
  '/app/code': typeof AppCodeRoute
  '/app/files': typeof AppFilesRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/notes': typeof AppNotesRoute
  '/app/translate': typeof AppTranslateRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/api-server': typeof SettingsApiServerRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/docprocess': typeof SettingsDocprocessRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/mcp': typeof SettingsMcpRouteWithChildren
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/model': typeof SettingsModelRoute
  '/settings/notes': typeof SettingsNotesRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/quickAssistant': typeof SettingsQuickAssistantRoute
  '/settings/quickphrase': typeof SettingsQuickphraseRoute
  '/settings/selectionAssistant': typeof SettingsSelectionAssistantRoute
  '/settings/shortcut': typeof SettingsShortcutRoute
  '/settings/websearch': typeof SettingsWebsearchRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/app/minapp/$appId': typeof AppMinappAppIdRoute
  '/app/paintings/$': typeof AppPaintingsSplatRoute
  '/settings/mcp/$': typeof SettingsMcpSplatRoute
  '/settings/mcp/builtin': typeof SettingsMcpBuiltinRoute
  '/settings/mcp/marketplaces': typeof SettingsMcpMarketplacesRoute
  '/settings/mcp/mcp-install': typeof SettingsMcpMcpInstallRoute
  '/settings/mcp/npx-search': typeof SettingsMcpNpxSearchRoute
  '/settings/mcp/servers': typeof SettingsMcpServersRoute
  '/settings/websearch/general': typeof SettingsWebsearchGeneralRoute
  '/app/minapp/': typeof AppMinappIndexRoute
  '/app/paintings/': typeof AppPaintingsIndexRoute
  '/settings/mcp/': typeof SettingsMcpIndexRoute
  '/settings/websearch/': typeof SettingsWebsearchIndexRoute
  '/settings/mcp/settings/$serverId': typeof SettingsMcpSettingsServerIdRoute
  '/settings/websearch/provider/$providerId': typeof SettingsWebsearchProviderProviderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/home': typeof HomeRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/chat': typeof AppChatRoute
  '/app/code': typeof AppCodeRoute
  '/app/files': typeof AppFilesRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/notes': typeof AppNotesRoute
  '/app/translate': typeof AppTranslateRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/api-server': typeof SettingsApiServerRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/docprocess': typeof SettingsDocprocessRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/model': typeof SettingsModelRoute
  '/settings/notes': typeof SettingsNotesRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/quickAssistant': typeof SettingsQuickAssistantRoute
  '/settings/quickphrase': typeof SettingsQuickphraseRoute
  '/settings/selectionAssistant': typeof SettingsSelectionAssistantRoute
  '/settings/shortcut': typeof SettingsShortcutRoute
  '/settings': typeof SettingsIndexRoute
  '/app/minapp/$appId': typeof AppMinappAppIdRoute
  '/app/paintings/$': typeof AppPaintingsSplatRoute
  '/settings/mcp/$': typeof SettingsMcpSplatRoute
  '/settings/mcp/builtin': typeof SettingsMcpBuiltinRoute
  '/settings/mcp/marketplaces': typeof SettingsMcpMarketplacesRoute
  '/settings/mcp/mcp-install': typeof SettingsMcpMcpInstallRoute
  '/settings/mcp/npx-search': typeof SettingsMcpNpxSearchRoute
  '/settings/mcp/servers': typeof SettingsMcpServersRoute
  '/settings/websearch/general': typeof SettingsWebsearchGeneralRoute
  '/app/minapp': typeof AppMinappIndexRoute
  '/app/paintings': typeof AppPaintingsIndexRoute
  '/settings/mcp': typeof SettingsMcpIndexRoute
  '/settings/websearch': typeof SettingsWebsearchIndexRoute
  '/settings/mcp/settings/$serverId': typeof SettingsMcpSettingsServerIdRoute
  '/settings/websearch/provider/$providerId': typeof SettingsWebsearchProviderProviderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/home': typeof HomeRoute
  '/settings': typeof SettingsRouteWithChildren
  '/app/assistant': typeof AppAssistantRoute
  '/app/chat': typeof AppChatRoute
  '/app/code': typeof AppCodeRoute
  '/app/files': typeof AppFilesRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/notes': typeof AppNotesRoute
  '/app/translate': typeof AppTranslateRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/api-server': typeof SettingsApiServerRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/docprocess': typeof SettingsDocprocessRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/mcp': typeof SettingsMcpRouteWithChildren
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/model': typeof SettingsModelRoute
  '/settings/notes': typeof SettingsNotesRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/quickAssistant': typeof SettingsQuickAssistantRoute
  '/settings/quickphrase': typeof SettingsQuickphraseRoute
  '/settings/selectionAssistant': typeof SettingsSelectionAssistantRoute
  '/settings/shortcut': typeof SettingsShortcutRoute
  '/settings/websearch': typeof SettingsWebsearchRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/app/minapp/$appId': typeof AppMinappAppIdRoute
  '/app/paintings/$': typeof AppPaintingsSplatRoute
  '/settings/mcp/$': typeof SettingsMcpSplatRoute
  '/settings/mcp/builtin': typeof SettingsMcpBuiltinRoute
  '/settings/mcp/marketplaces': typeof SettingsMcpMarketplacesRoute
  '/settings/mcp/mcp-install': typeof SettingsMcpMcpInstallRoute
  '/settings/mcp/npx-search': typeof SettingsMcpNpxSearchRoute
  '/settings/mcp/servers': typeof SettingsMcpServersRoute
  '/settings/websearch/general': typeof SettingsWebsearchGeneralRoute
  '/app/minapp/': typeof AppMinappIndexRoute
  '/app/paintings/': typeof AppPaintingsIndexRoute
  '/settings/mcp/': typeof SettingsMcpIndexRoute
  '/settings/websearch/': typeof SettingsWebsearchIndexRoute
  '/settings/mcp/settings/$serverId': typeof SettingsMcpSettingsServerIdRoute
  '/settings/websearch/provider/$providerId': typeof SettingsWebsearchProviderProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/home'
    | '/settings'
    | '/app/assistant'
    | '/app/chat'
    | '/app/code'
    | '/app/files'
    | '/app/knowledge'
    | '/app/notes'
    | '/app/translate'
    | '/settings/about'
    | '/settings/api-server'
    | '/settings/data'
    | '/settings/display'
    | '/settings/docprocess'
    | '/settings/general'
    | '/settings/mcp'
    | '/settings/memory'
    | '/settings/model'
    | '/settings/notes'
    | '/settings/provider'
    | '/settings/quickAssistant'
    | '/settings/quickphrase'
    | '/settings/selectionAssistant'
    | '/settings/shortcut'
    | '/settings/websearch'
    | '/settings/'
    | '/app/minapp/$appId'
    | '/app/paintings/$'
    | '/settings/mcp/$'
    | '/settings/mcp/builtin'
    | '/settings/mcp/marketplaces'
    | '/settings/mcp/mcp-install'
    | '/settings/mcp/npx-search'
    | '/settings/mcp/servers'
    | '/settings/websearch/general'
    | '/app/minapp/'
    | '/app/paintings/'
    | '/settings/mcp/'
    | '/settings/websearch/'
    | '/settings/mcp/settings/$serverId'
    | '/settings/websearch/provider/$providerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/home'
    | '/app/assistant'
    | '/app/chat'
    | '/app/code'
    | '/app/files'
    | '/app/knowledge'
    | '/app/notes'
    | '/app/translate'
    | '/settings/about'
    | '/settings/api-server'
    | '/settings/data'
    | '/settings/display'
    | '/settings/docprocess'
    | '/settings/general'
    | '/settings/memory'
    | '/settings/model'
    | '/settings/notes'
    | '/settings/provider'
    | '/settings/quickAssistant'
    | '/settings/quickphrase'
    | '/settings/selectionAssistant'
    | '/settings/shortcut'
    | '/settings'
    | '/app/minapp/$appId'
    | '/app/paintings/$'
    | '/settings/mcp/$'
    | '/settings/mcp/builtin'
    | '/settings/mcp/marketplaces'
    | '/settings/mcp/mcp-install'
    | '/settings/mcp/npx-search'
    | '/settings/mcp/servers'
    | '/settings/websearch/general'
    | '/app/minapp'
    | '/app/paintings'
    | '/settings/mcp'
    | '/settings/websearch'
    | '/settings/mcp/settings/$serverId'
    | '/settings/websearch/provider/$providerId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/home'
    | '/settings'
    | '/app/assistant'
    | '/app/chat'
    | '/app/code'
    | '/app/files'
    | '/app/knowledge'
    | '/app/notes'
    | '/app/translate'
    | '/settings/about'
    | '/settings/api-server'
    | '/settings/data'
    | '/settings/display'
    | '/settings/docprocess'
    | '/settings/general'
    | '/settings/mcp'
    | '/settings/memory'
    | '/settings/model'
    | '/settings/notes'
    | '/settings/provider'
    | '/settings/quickAssistant'
    | '/settings/quickphrase'
    | '/settings/selectionAssistant'
    | '/settings/shortcut'
    | '/settings/websearch'
    | '/settings/'
    | '/app/minapp/$appId'
    | '/app/paintings/$'
    | '/settings/mcp/$'
    | '/settings/mcp/builtin'
    | '/settings/mcp/marketplaces'
    | '/settings/mcp/mcp-install'
    | '/settings/mcp/npx-search'
    | '/settings/mcp/servers'
    | '/settings/websearch/general'
    | '/app/minapp/'
    | '/app/paintings/'
    | '/settings/mcp/'
    | '/settings/websearch/'
    | '/settings/mcp/settings/$serverId'
    | '/settings/websearch/provider/$providerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HomeRoute: typeof HomeRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/websearch': {
      id: '/settings/websearch'
      path: '/websearch'
      fullPath: '/settings/websearch'
      preLoaderRoute: typeof SettingsWebsearchRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/shortcut': {
      id: '/settings/shortcut'
      path: '/shortcut'
      fullPath: '/settings/shortcut'
      preLoaderRoute: typeof SettingsShortcutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/selectionAssistant': {
      id: '/settings/selectionAssistant'
      path: '/selectionAssistant'
      fullPath: '/settings/selectionAssistant'
      preLoaderRoute: typeof SettingsSelectionAssistantRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/quickphrase': {
      id: '/settings/quickphrase'
      path: '/quickphrase'
      fullPath: '/settings/quickphrase'
      preLoaderRoute: typeof SettingsQuickphraseRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/quickAssistant': {
      id: '/settings/quickAssistant'
      path: '/quickAssistant'
      fullPath: '/settings/quickAssistant'
      preLoaderRoute: typeof SettingsQuickAssistantRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/provider': {
      id: '/settings/provider'
      path: '/provider'
      fullPath: '/settings/provider'
      preLoaderRoute: typeof SettingsProviderRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notes': {
      id: '/settings/notes'
      path: '/notes'
      fullPath: '/settings/notes'
      preLoaderRoute: typeof SettingsNotesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/model': {
      id: '/settings/model'
      path: '/model'
      fullPath: '/settings/model'
      preLoaderRoute: typeof SettingsModelRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/memory': {
      id: '/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof SettingsMemoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/docprocess': {
      id: '/settings/docprocess'
      path: '/docprocess'
      fullPath: '/settings/docprocess'
      preLoaderRoute: typeof SettingsDocprocessRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/display': {
      id: '/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof SettingsDisplayRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-server': {
      id: '/settings/api-server'
      path: '/api-server'
      fullPath: '/settings/api-server'
      preLoaderRoute: typeof SettingsApiServerRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/app/translate': {
      id: '/app/translate'
      path: '/translate'
      fullPath: '/app/translate'
      preLoaderRoute: typeof AppTranslateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/files': {
      id: '/app/files'
      path: '/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/code': {
      id: '/app/code'
      path: '/code'
      fullPath: '/app/code'
      preLoaderRoute: typeof AppCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/settings/websearch/': {
      id: '/settings/websearch/'
      path: '/'
      fullPath: '/settings/websearch/'
      preLoaderRoute: typeof SettingsWebsearchIndexRouteImport
      parentRoute: typeof SettingsWebsearchRoute
    }
    '/settings/mcp/': {
      id: '/settings/mcp/'
      path: '/'
      fullPath: '/settings/mcp/'
      preLoaderRoute: typeof SettingsMcpIndexRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/app/paintings/': {
      id: '/app/paintings/'
      path: '/paintings'
      fullPath: '/app/paintings/'
      preLoaderRoute: typeof AppPaintingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/minapp/': {
      id: '/app/minapp/'
      path: '/minapp'
      fullPath: '/app/minapp/'
      preLoaderRoute: typeof AppMinappIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/settings/websearch/general': {
      id: '/settings/websearch/general'
      path: '/general'
      fullPath: '/settings/websearch/general'
      preLoaderRoute: typeof SettingsWebsearchGeneralRouteImport
      parentRoute: typeof SettingsWebsearchRoute
    }
    '/settings/mcp/servers': {
      id: '/settings/mcp/servers'
      path: '/servers'
      fullPath: '/settings/mcp/servers'
      preLoaderRoute: typeof SettingsMcpServersRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/npx-search': {
      id: '/settings/mcp/npx-search'
      path: '/npx-search'
      fullPath: '/settings/mcp/npx-search'
      preLoaderRoute: typeof SettingsMcpNpxSearchRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/mcp-install': {
      id: '/settings/mcp/mcp-install'
      path: '/mcp-install'
      fullPath: '/settings/mcp/mcp-install'
      preLoaderRoute: typeof SettingsMcpMcpInstallRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/marketplaces': {
      id: '/settings/mcp/marketplaces'
      path: '/marketplaces'
      fullPath: '/settings/mcp/marketplaces'
      preLoaderRoute: typeof SettingsMcpMarketplacesRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/builtin': {
      id: '/settings/mcp/builtin'
      path: '/builtin'
      fullPath: '/settings/mcp/builtin'
      preLoaderRoute: typeof SettingsMcpBuiltinRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/$': {
      id: '/settings/mcp/$'
      path: '/$'
      fullPath: '/settings/mcp/$'
      preLoaderRoute: typeof SettingsMcpSplatRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/app/paintings/$': {
      id: '/app/paintings/$'
      path: '/paintings/$'
      fullPath: '/app/paintings/$'
      preLoaderRoute: typeof AppPaintingsSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/minapp/$appId': {
      id: '/app/minapp/$appId'
      path: '/minapp/$appId'
      fullPath: '/app/minapp/$appId'
      preLoaderRoute: typeof AppMinappAppIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/settings/websearch/provider/$providerId': {
      id: '/settings/websearch/provider/$providerId'
      path: '/provider/$providerId'
      fullPath: '/settings/websearch/provider/$providerId'
      preLoaderRoute: typeof SettingsWebsearchProviderProviderIdRouteImport
      parentRoute: typeof SettingsWebsearchRoute
    }
    '/settings/mcp/settings/$serverId': {
      id: '/settings/mcp/settings/$serverId'
      path: '/settings/$serverId'
      fullPath: '/settings/mcp/settings/$serverId'
      preLoaderRoute: typeof SettingsMcpSettingsServerIdRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppChatRoute: typeof AppChatRoute
  AppCodeRoute: typeof AppCodeRoute
  AppFilesRoute: typeof AppFilesRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppNotesRoute: typeof AppNotesRoute
  AppTranslateRoute: typeof AppTranslateRoute
  AppMinappAppIdRoute: typeof AppMinappAppIdRoute
  AppPaintingsSplatRoute: typeof AppPaintingsSplatRoute
  AppMinappIndexRoute: typeof AppMinappIndexRoute
  AppPaintingsIndexRoute: typeof AppPaintingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppChatRoute: AppChatRoute,
  AppCodeRoute: AppCodeRoute,
  AppFilesRoute: AppFilesRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppNotesRoute: AppNotesRoute,
  AppTranslateRoute: AppTranslateRoute,
  AppMinappAppIdRoute: AppMinappAppIdRoute,
  AppPaintingsSplatRoute: AppPaintingsSplatRoute,
  AppMinappIndexRoute: AppMinappIndexRoute,
  AppPaintingsIndexRoute: AppPaintingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SettingsMcpRouteChildren {
  SettingsMcpSplatRoute: typeof SettingsMcpSplatRoute
  SettingsMcpBuiltinRoute: typeof SettingsMcpBuiltinRoute
  SettingsMcpMarketplacesRoute: typeof SettingsMcpMarketplacesRoute
  SettingsMcpMcpInstallRoute: typeof SettingsMcpMcpInstallRoute
  SettingsMcpNpxSearchRoute: typeof SettingsMcpNpxSearchRoute
  SettingsMcpServersRoute: typeof SettingsMcpServersRoute
  SettingsMcpIndexRoute: typeof SettingsMcpIndexRoute
  SettingsMcpSettingsServerIdRoute: typeof SettingsMcpSettingsServerIdRoute
}

const SettingsMcpRouteChildren: SettingsMcpRouteChildren = {
  SettingsMcpSplatRoute: SettingsMcpSplatRoute,
  SettingsMcpBuiltinRoute: SettingsMcpBuiltinRoute,
  SettingsMcpMarketplacesRoute: SettingsMcpMarketplacesRoute,
  SettingsMcpMcpInstallRoute: SettingsMcpMcpInstallRoute,
  SettingsMcpNpxSearchRoute: SettingsMcpNpxSearchRoute,
  SettingsMcpServersRoute: SettingsMcpServersRoute,
  SettingsMcpIndexRoute: SettingsMcpIndexRoute,
  SettingsMcpSettingsServerIdRoute: SettingsMcpSettingsServerIdRoute,
}

const SettingsMcpRouteWithChildren = SettingsMcpRoute._addFileChildren(
  SettingsMcpRouteChildren,
)

interface SettingsWebsearchRouteChildren {
  SettingsWebsearchGeneralRoute: typeof SettingsWebsearchGeneralRoute
  SettingsWebsearchIndexRoute: typeof SettingsWebsearchIndexRoute
  SettingsWebsearchProviderProviderIdRoute: typeof SettingsWebsearchProviderProviderIdRoute
}

const SettingsWebsearchRouteChildren: SettingsWebsearchRouteChildren = {
  SettingsWebsearchGeneralRoute: SettingsWebsearchGeneralRoute,
  SettingsWebsearchIndexRoute: SettingsWebsearchIndexRoute,
  SettingsWebsearchProviderProviderIdRoute:
    SettingsWebsearchProviderProviderIdRoute,
}

const SettingsWebsearchRouteWithChildren =
  SettingsWebsearchRoute._addFileChildren(SettingsWebsearchRouteChildren)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsApiServerRoute: typeof SettingsApiServerRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsDisplayRoute: typeof SettingsDisplayRoute
  SettingsDocprocessRoute: typeof SettingsDocprocessRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsMcpRoute: typeof SettingsMcpRouteWithChildren
  SettingsMemoryRoute: typeof SettingsMemoryRoute
  SettingsModelRoute: typeof SettingsModelRoute
  SettingsNotesRoute: typeof SettingsNotesRoute
  SettingsProviderRoute: typeof SettingsProviderRoute
  SettingsQuickAssistantRoute: typeof SettingsQuickAssistantRoute
  SettingsQuickphraseRoute: typeof SettingsQuickphraseRoute
  SettingsSelectionAssistantRoute: typeof SettingsSelectionAssistantRoute
  SettingsShortcutRoute: typeof SettingsShortcutRoute
  SettingsWebsearchRoute: typeof SettingsWebsearchRouteWithChildren
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsApiServerRoute: SettingsApiServerRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsDisplayRoute: SettingsDisplayRoute,
  SettingsDocprocessRoute: SettingsDocprocessRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsMcpRoute: SettingsMcpRouteWithChildren,
  SettingsMemoryRoute: SettingsMemoryRoute,
  SettingsModelRoute: SettingsModelRoute,
  SettingsNotesRoute: SettingsNotesRoute,
  SettingsProviderRoute: SettingsProviderRoute,
  SettingsQuickAssistantRoute: SettingsQuickAssistantRoute,
  SettingsQuickphraseRoute: SettingsQuickphraseRoute,
  SettingsSelectionAssistantRoute: SettingsSelectionAssistantRoute,
  SettingsShortcutRoute: SettingsShortcutRoute,
  SettingsWebsearchRoute: SettingsWebsearchRouteWithChildren,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HomeRoute: HomeRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
