/**
 * Auto-generated icon meta catalog for synchronous runtime lookup
 * Do not edit manually — regenerated by the icon pipeline
 *
 * Generated at: 2026-07-11T04:47:13.140Z
 * Total icons: 36
 */
import { type IconMeta } from '../types'
import { meta as ayaMeta } from './aya/meta'
import { meta as claudeMeta } from './claude/meta'
import { meta as codegeexMeta } from './codegeex/meta'
import { meta as doubaoMeta } from './doubao/meta'
import { meta as geminiMeta } from './gemini/meta'
import { meta as gemmaMeta } from './gemma/meta'
import { meta as glmMeta } from './glm/meta'
import { meta as gpt5Meta } from './gpt-5/meta'
import { meta as gpt51Meta } from './gpt-5-1/meta'
import { meta as gpt51ChatMeta } from './gpt-5-1-chat/meta'
import { meta as gpt51CodexMeta } from './gpt-5-1-codex/meta'
import { meta as gpt51CodexMiniMeta } from './gpt-5-1-codex-mini/meta'
import { meta as gpt52Meta } from './gpt-5-2/meta'
import { meta as gpt52ProMeta } from './gpt-5-2-pro/meta'
import { meta as gpt5ChatMeta } from './gpt-5-chat/meta'
import { meta as gpt5CodexMeta } from './gpt-5-codex/meta'
import { meta as gpt5MiniMeta } from './gpt-5-mini/meta'
import { meta as gpt5NanoMeta } from './gpt-5-nano/meta'
import { meta as gptImage1Meta } from './gpt-image-1/meta'
import { meta as gptImage15Meta } from './gpt-image-1-5/meta'
import { meta as gptOss20bMeta } from './gpt-oss-20b/meta'
import { meta as gptOss120bMeta } from './gpt-oss-120b/meta'
import { meta as grokMeta } from './grok/meta'
import { meta as hailuoMeta } from './hailuo/meta'
import { meta as happyhorseMeta } from './happyhorse/meta'
import { meta as hunyuanMeta } from './hunyuan/meta'
import { meta as ibmMeta } from './ibm/meta'
import { meta as kimiMeta } from './kimi/meta'
import { meta as lingMeta } from './ling/meta'
import { meta as mimoMeta } from './mimo/meta'
import { meta as novaMeta } from './nova/meta'
import { meta as palmMeta } from './palm/meta'
import { meta as qwenMeta } from './qwen/meta'
import { meta as sensenovaMeta } from './sensenova/meta'
import { meta as soraMeta } from './sora/meta'
import { meta as trinityMeta } from './trinity/meta'

export const MODEL_ICON_META_CATALOG = {
  aya: ayaMeta,
  claude: claudeMeta,
  codegeex: codegeexMeta,
  doubao: doubaoMeta,
  gemini: geminiMeta,
  gemma: gemmaMeta,
  glm: glmMeta,
  'gpt-5': gpt5Meta,
  'gpt-5-1': gpt51Meta,
  'gpt-5-1-chat': gpt51ChatMeta,
  'gpt-5-1-codex': gpt51CodexMeta,
  'gpt-5-1-codex-mini': gpt51CodexMiniMeta,
  'gpt-5-2': gpt52Meta,
  'gpt-5-2-pro': gpt52ProMeta,
  'gpt-5-chat': gpt5ChatMeta,
  'gpt-5-codex': gpt5CodexMeta,
  'gpt-5-mini': gpt5MiniMeta,
  'gpt-5-nano': gpt5NanoMeta,
  'gpt-image-1': gptImage1Meta,
  'gpt-image-1-5': gptImage15Meta,
  'gpt-oss-120b': gptOss120bMeta,
  'gpt-oss-20b': gptOss20bMeta,
  grok: grokMeta,
  hailuo: hailuoMeta,
  happyhorse: happyhorseMeta,
  hunyuan: hunyuanMeta,
  ibm: ibmMeta,
  kimi: kimiMeta,
  ling: lingMeta,
  mimo: mimoMeta,
  nova: novaMeta,
  palm: palmMeta,
  qwen: qwenMeta,
  sensenova: sensenovaMeta,
  sora: soraMeta,
  trinity: trinityMeta
} as const satisfies Record<string, IconMeta>

export type ModelIconKey = keyof typeof MODEL_ICON_META_CATALOG
